// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function reducer(state, action) {
  if (action) {
    return {
            unsavedChanges: false,
            tool: state.tool
          };
  } else {
    return {
            unsavedChanges: true,
            tool: state.tool
          };
  }
}

export {
  reducer ,
  
}
/* No side effect */
