image: node:10.15.1

pipelines:
  pull-requests:
    '**':
      - step:
          caches:
            - node
          script:
            - npm ci
            - npm run lint
            - npm run typecheck
            - npm test
  branches:
    master:
      - step:
          caches:
            - node
          script:
            - npm ci
            - npm run lint
            - npm run typecheck
            - npm test
            - npx now --token=$NOW_TOKEN
