image: node:10.15.1

pipelines:
  pull-requests:
    '**':
      - step:
          caches:
            - node
          script:
            - npm ci
            - npm run lint
            - npm run typecheck
            - npm test
  branches:
    master:
      - step:
          name: 'Lint/typecheck/test'
          caches:
            - node
          script:
            - npm ci
            - npm run lint
            - npm run typecheck
            - npm test
      - step:
          name: 'Deploy to now'
          script:
            - npm install -g now
            - now --token=$NOW_TOKEN
