image: node:10.15.1

pipelines:
  pull-requests:
    '**':
      - step:
          name: 'Test and build'
          caches:
            - node
          script:
            - npm ci
            - npm test
            - npm run build
  branches:
    master:
      - step:
          name: 'Deploy to now'
          deployment: 'Production'
          script:
            - npm install -g now
            - now --token=$NOW_TOKEN --target production
