image: node:10.15.1

pipelines:
  pull-requests:
    '**':
      - step:
          name: 'Test and build'
          caches:
            - node
          script:
            - npm ci
            - npm test
            - npm run build
  branches:
    master:
      - step:
          name: 'Deploy Firebase Rules'
          deployment: firebase-prod
          caches:
            - node
          script:
            - npm install -g firebase-tools
            - firebase deploy --only firestore --token=$FIREBASE_TOKEN --project=$FIREBASE_PROJECT --non-interactive
      - step:
          name: 'Deploy to now'
          deployment: now-prod
          caches:
            - node
          script:
            - npm install -g now
            - now --token=$NOW_TOKEN --target production
