image: node:10.15.1

pipelines:
  pull-requests:
    '**':
      # - step:
      #     name: 'Test and build'
      #     caches:
      #       - node
      #     script:
      #       - npm ci
      #       - npm test
      #       - npm run build
      - step:
          name: 'Temp Now'
          deployment: now-prod
          caches:
            - node
          script:
            - npm install -g now
            - now --token=$NOW_TOKEN --target staging -e REACT_APP_FIREBASE_API_KEY=$REACT_APP_FIREBASE_API_KEY -e REACT_APP_FIREBASE_AUTH_DOMAIN=$REACT_APP_FIREBASE_AUTH_DOMAIN -e REACT_APP_FIREBASE_DATABASE_URL=$REACT_APP_FIREBASE_DATABASE_URL -e REACT_APP_FIREBASE_PROJECT_ID=$REACT_APP_FIREBASE_PROJECT_ID -e REACT_APP_FIREBASE_STORAGE_BUCKET=$REACT_APP_FIREBASE_STORAGE_BUCKET -e REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$REACT_APP_FIREBASE_MESSAGING_SENDER_ID -e REACT_APP_FIREBASE_APP_ID=$REACT_APP_FIREBASE_APP_ID
  branches:
    master:
      - step:
          name: 'Deploy Firebase Rules'
          deployment: firebase-prod
          caches:
            - node
          script:
            - npm install -g firebase-tools
            - firebase deploy --only firestore --token=$FIREBASE_TOKEN --project=$FIREBASE_PROJECT --non-interactive
      - step:
          name: 'Deploy to now'
          deployment: now-prod
          caches:
            - node
          script:
            - npm install -g now
            - now --token=$NOW_TOKEN --target production
