image: node:10.15.1

pipelines:
  pull-requests:
    '**':
      - step:
          name: 'List/typecheck/test'
          caches:
            - node
          script:
            - npm ci
            - npm test
            - npm run build
  branches:
    master:
      - step:
          name: 'Deploy to now'
          script:
            - npm install -g now
            - now --token=$NOW_TOKEN
