export default `
(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]
RU[Japanese]SZ[19]KM[0.00]
PW[White]PB[Black]
;B[pd]GB[1]
;W[dd]GW[1]
;B[pp]GB[2]HO[2]
;W[dp]N[This move has a name]C[This is just to test out names and comments]GW[2]
;AB[jf][jg][jh][ji][jj]
  AW[kf][kg][kh][ki][kj]
  CR[ih][jh][kh]
  LB[ii:A][ji:B][ki:C][ij:1][jj:2][kj:3]
  TR[if][jf][kf]
  SQ[ig][jg][kg]
  LN[ad:fg][ll:bo][ca:cm][ad:md]
  SL[pd][dd][kk][aa][ab][bb]
  DD[ff][fg][fh]
  MA[qq]
  AR[qs:lg]
  DM[2]
;W[gg]UC[1]
;B[ll]V[5.5]
)
`;
