export default `
(;GM[1]FF[4]CA[UTF-8]AP[CGoban:2]ST[2]
RU[Japanese]SZ[19]KM[0.00]TM[]
PW[Sorin Gherman]PB[Anton Zatonskikh]DT[1994-07-03]EV[D class]C[Anton was one of the few non-asian inseis (he's Russian). His Go was very territorial.
We played this game in D class: it was my 3rd month as an insei: first was in D, were I easily promoted to C. Second was in C, were I easily fall back to D :-).
For Anton this was his first month as an insei.

Game commentary by Hans Pietsch ( http://gobase.org/information/players/?pp=Hans%20Pietsch ), A class insei at that time, later promoted until 4 dan pro).
]RE[W+Resign]
;B[dp]
;W[pd]
;B[cd]
;W[pp]
;B[ec]
;W[cj]
;B[ch]
;W[cn]
;B[cl]
;W[en]
;B[fp]
;W[dk]
;B[co]
;W[bn]
;B[qj]
(;W[jc]LB[hq:a]C[White can play more actively at "a". See the variation diagram.]
;B[hc]C[Too slow.]
;W[fk]
(;B[dn]LB[jq:a]C[Better extend at "a".]
;W[dm]
;B[do]
;W[cm]
;B[qm]
;W[mq]
(;B[rp]LB[nc:a]C[Should better attack white's position at "a" (O17).]
(;W[bo]LB[ip:a]C[Better at "a". See the variation.]
;B[kq]
;W[qq]
;B[cq]
;W[je]
(;B[qf]LB[ob:a]C[Better invade deeply form the other side, at "a".]HO[]
;W[qd]
(;B[of]LB[md:a]C[Tool slow: better invade at "a".]
;W[nd]
;B[rq]
(;W[qh]LB[mo:a]C[White should defend at "a" (tobi).]
;B[pi]
;W[ph]
;B[oh]
;W[rf]
;B[oq]
(;W[pr]LB[op:a]C[Shold defend at "s". See variation.]
;B[nq]
;W[mp]
;B[oo]
;W[jq]
;B[no]
;W[kr]
(;B[hq]LB[mr:a]C[At "a" is more severe.]
;W[nr]
;B[or]
;W[os]
;B[mr]
;W[ns]
;B[pq]
;W[qr]
;B[qp]C[Black should win after this, anyway.

The game commentary ends here.]
;W[lr]
;B[ni]
;W[cf]
;B[df]
;W[cg]
;B[dg]
;W[ce]
;B[dd]
;W[bh]
;B[dh]
;W[ci]
;B[rg]
;W[qg]
;B[pf]
;W[rh]
;B[re]
;W[sg]
;B[qe]
;W[rj]
;B[rk]
;W[qi]
;B[qk]
;W[sk]
;B[sl]
;W[sj]
;B[rc]
;W[qb]
;B[bp]
;W[ng]
;B[og]
;W[pj]
;B[oi]
;W[ib]
;B[hb]
;W[rl]
;B[ql]
;W[de]
;B[ee]
;W[be]
;B[bd]
;W[ad]
;B[ac]
;W[ae]
;B[bc]
;W[ir]
;B[hr]
;W[ml]
;B[nk]
;W[ef]
;B[fe]
;W[ff]
;B[gf]
;W[fg]
;B[gg]
;W[fh]
;B[gh]
;W[gi]
;B[hi]
;W[gj]C[Subsequent moves omitted. White won by resign.])
(;B[mr]CR[mr]C[More severe.]))
(;W[op]LB[oi:a]C[White should defend here in order to become strong in the center and aim at the cut at "a".]
;B[nq]
;W[np]
;B[mr]
;W[lr]
;B[lq]
;W[mp]
;B[or]
;W[ko]
;B[ip]
;W[oi]C[Very severe, especially after white became thicker on the lower side.]
;B[nh]
;W[oj]
;B[mi]
;W[ol]))
(;W[mo]CR[mo]C[Defend.]))
(;B[md]CR[md]C[Invade.]))
(;B[ob]CR[ob]C[Aggresive.]))
(;W[ip]C[This is bigger than the corner. And white gets sente to play on the upper side, too.]
;B[bo]
;W[je]))
(;B[nc]CR[nc]C[Attack.]))
(;B[jq]CR[jq]C[Normal fuseki move.]))
(;W[hq]C[This is hitting black's weakest point on the board.]
;B[go]
;W[ho]
;B[hn]
;W[io]))
`;
