// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as SpeedDial$KifuIo from "../../common/SpeedDial.bs.js";

function EditingToolsSpeedDial(Props) {
  var direction = Props.direction;
  var children = Props.children;
  return React.createElement(SpeedDial$KifuIo.make, {
              direction: direction,
              children: children
            });
}

var make = EditingToolsSpeedDial;

export {
  make ,
  
}
/* react Not a pure module */
