// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_mapperRt from "./../../../node_modules/bs-platform/lib/es6/js_mapperRt.js";
import * as SpeedDialTsx from "../../components/SpeedDial.tsx";

var make = SpeedDialTsx.default;

var BaseSpeedDial = {
  make: make
};

var jsMapperConstantArray = [
  /* tuple */[
    19067,
    "UP"
  ],
  /* tuple */[
    759637122,
    "DOWN"
  ],
  /* tuple */[
    847852583,
    "LEFT"
  ]
];

function directionToJs(param) {
  return Js_mapperRt.binarySearch(3, param, jsMapperConstantArray);
}

function directionFromJs(param) {
  return Js_mapperRt.revSearch(3, jsMapperConstantArray, param);
}

function SpeedDial(Props) {
  var direction = Props.direction;
  var children = Props.children;
  var directionStr = direction !== undefined ? directionToJs(direction) : undefined;
  return React.createElement(make, {
              direction: directionStr,
              children: children
            });
}

var make$1 = SpeedDial;

export {
  BaseSpeedDial ,
  directionToJs ,
  directionFromJs ,
  make$1 as make,
  
}
/* make Not a pure module */
