// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as SpeedDialTsx from "../../components/SpeedDial.tsx";

var make = SpeedDialTsx.default;

var BaseSpeedDial = {
  make: make
};

function SpeedDial(Props) {
  var direction = Props.direction;
  var children = Props.children;
  var directionStr;
  if (direction !== undefined) {
    switch (direction) {
      case /* Up */0 :
          directionStr = "UP";
          break;
      case /* Down */1 :
          directionStr = "DOWN";
          break;
      case /* Left */2 :
          directionStr = "LEFT";
          break;
      
    }
  } else {
    directionStr = undefined;
  }
  return React.createElement(make, {
              direction: directionStr,
              children: children
            });
}

var make$1 = SpeedDial;

export {
  BaseSpeedDial ,
  make$1 as make,
  
}
/* make Not a pure module */
