// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as SpeedDialOptionTsx from "../../components/SpeedDialOption.tsx";

var make = SpeedDialOptionTsx.default;

var BaseSpeedDialOption = {
  make: make
};

function SpeedDialOption(Props) {
  var size = Props.size;
  var children = Props.children;
  var label = Props.label;
  var labelAbove = Props.labelAbove;
  var highlighted = Props.highlighted;
  var sizeStr = size !== undefined ? (
      size ? "SMALL" : "MEDIUM"
    ) : undefined;
  return React.createElement(make, {
              label: label,
              children: children,
              labelAbove: labelAbove,
              highlighted: highlighted,
              size: sizeStr
            });
}

var make$1 = SpeedDialOption;

export {
  BaseSpeedDialOption ,
  make$1 as make,
  
}
/* make Not a pure module */
