// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as List from "./../../../node_modules/bs-platform/lib/es6/list.js";

function captureCountReducer(state, action) {
  if (typeof action === "number") {
    return state;
  } else {
    var points = action[0];
    if (action[1]) {
      return {
              b: state.b,
              w: state.w + List.length(points) | 0
            };
    } else {
      return {
              b: state.b + List.length(points) | 0,
              w: state.w
            };
    }
  }
}

var thing = /* Capture */[
  /* :: */[
    "hi",
    /* [] */0
  ],
  /* Black */0
];

export {
  captureCountReducer ,
  thing ,
  
}
/* No side effect */
