// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function updateCaptureCount(state, points, color) {
  var numCaptures = points.length;
  switch (color) {
    case "b" :
        return {
                b: state.b,
                w: numCaptures + state.w | 0
              };
    case "w" :
        return {
                b: numCaptures + state.b | 0,
                w: state.w
              };
    default:
      return state;
  }
}

var defaultCaptureCounts = {
  b: 0,
  w: 0
};

export {
  defaultCaptureCounts ,
  updateCaptureCount ,
  
}
/* No side effect */
