// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function stoneColorString(color) {
  if (color) {
    return "w";
  } else {
    return "b";
  }
}

export {
  stoneColorString ,
  
}
/* No side effect */
